### ISSUE TITLE
alpha channel is needed

### ISSUE THREAD

**Issue by macrozone** [Loilo/color-blend#1]
I found this package in this comment: https://github.com/Qix-/color/issues/99#issuecomment-266601291

i thought that it would be directly compatible with color, but its not totally:

e.g. this leads to wrong results, because color-blends needs an alpha channel (property `a`):

```
import Color from 'color'
import blender from 'color-blend'


const color1 = Color("#B5E684")
const colorBlended = blender.normal(color1, Color("yellow")) // returns {r: NaN, g: NaN, b: NaN, a: NaN}

```

**Comment by Loilo** [comment]
No, it's not the goal of this package to be specifically compatible with the `Color` package. Its approach is a little more broad.

However, it should not be too hard to write a wrapper that does so:

```javascript
import Color from 'color'
import blender from 'color-blend'

export default Object.keys(blender).reduce((carry, prop) => Object.assign({}, carry,
  prop === 'options'
    ? {}
    : {
      [prop]: (backdrop, source) => {
        const { r, g, b, a } = blender[prop]({
          r: backdrop.red(),
          g: backdrop.green(),
          b: backdrop.blue(),
          a: backdrop.alpha()
        }, {
          r: source.red(),
          g: source.green(),
          b: source.blue(),
          a: source.alpha()
        })
        
        return Color({ r, g, b, alpha: a })
      }
    }
), {})
```

This exports a version of the blender that takes two `Color` objects and also returns a `Color` object.

I've not tested it extensively but the few cases I've tried worked fine.
