### ISSUE TITLE
Renfactor input / output parameters

### ISSUE THREAD

**Issue by TerekhovAI** [loilo/color-blend#19]
Hello! Thank you very much for time and efforts put into this library.
May i draw your attention to one nuance?

I'm trying to use your great library with `polished` npm-package, cause i work on design-system and i need to blend some colors, with blend-modes, but i need to put some extra time because of the following.

**Issue**
Function `rgba` from `polished` works as follows
rgba(255, 205, 100, 0.7) or rgba({ red: 255, green: 205, blue: 100, alpha: 0.7 })

But you package's output is { r: number, g: number, b: number, a: number }. so in order to use `polished` i need to write 2 functions
1st - to convert any `polished` result to entry format of your library
2nd - convert your library output to format, that `polished` understands

**My proposal**
Please, make `color-blend` output format either / or
a) an object `{ red: number, green: number, blue: number, alpha: number }`
b) array of RGBA values as numbers  [, , , ,] which then can be passed with ...spread syntax out of the box

This can be achieved either / or
1) With some optional parameters to functions, which will determine output format
2) Writing alternatively-named functions, similar to like you did in `color-blend/unit`

**P.S.**
With all the respect, it is just a proposal.
I dont have any problems writing such functions on my own in my project.
I just think this could help other people to use your library in more wide and flexible way, thats all.

Best wishes and kind regards,
Artemiy

**Comment by loilo** [comment]
Hey there.

Thanks for the suggestion, and sorry for coming back to you so late on this. I guess this is no longer relevant for you, but here's to others who have the same suggestion:

I generally want to keep this package as small and focused as possible, therefore I have settled on two input modes (RGBA 8bit based and RGBA unit-based) and will not provide further conversion.

However, it's relatively easy to create your own wrapper for the library to work, for example, with the [`color`](https://npmjs.com/package/color) library.

I have implemented such a wrapper in another issue, see [this comment](https://github.com/loilo/color-blend/issues/1#issuecomment-331273701).
