### ISSUE TITLE
Is this useful for rgb correction in photos?

### ISSUE THREAD

**Issue by tylerssn** [loilo/color-blend#29]
I'm new to color blending. If I have a pixel in the photo that represents true red, green and then blue, based on how much each of these is off can I use this library to correct the pixels in the rest of the image?

For example if red in the photo appears as 240,13,85 when it should be 255,0,0 I'd like to apply the correction to the rest of the pixels. Same for the green pixel and blue.

**Comment by loilo** [comment]
No, that's generally not what blend modes are for. The process you're describing is called "color balance" or "white balance", so you may want to search the web for that. :)
