### ISSUE TITLE
Is there a method getHue/setHue?

### ISSUE THREAD

**Issue by army8735** [loilo/color-blend#33]
I have found getLuminosity/setLuminosity/getSaturation/setSaturation, but I want to change hue of a color.

**Comment by loilo** [comment]
Hey @army8735, thanks for the question.

This is not a generic color modification library, its only purpose is to blend colors. For a more powerful color handling tool, you may want to take a look at the [`color`](https://www.npmjs.com/package/color) package.

That said, if you're willing to jump some hoops, you *can* change the hue of a color with this library by blending a color with the desired hue value onto your base color, in `hue` mode:

```js
import { hue } from 'color-blend'

const darkRed = { r: 128, g: 0, b: 0, a: 1 }
const brightGreen = { r: 0, g: 255, b: 0, a: 1 }

const darkGreen = hue(darkRed, brightGreen)
```
